(begin
  (load "load-module.scm")
  (load-module 'utils)
  (load-module 'destructive-ops)
  (load-module 'format)
  (load-module 'assert)
  (load-module 'mergesort)
  (load-module 'pregexp)
  (load-module 'apropos)
  (load-module 'binary-search)
  (load-module 'binary-tree))
