(define-syntax with-timing-output
  (syntax-rules ()
    ((with-timing-output body)
     (with-timings 
         (lambda () body) 
       (lambda (run-time gc-time real-time)
         (display ";Run time:\t")
         (write (internal-time/ticks->seconds run-time))
         (newline)
         (display ";GC time:\t")
         (write (internal-time/ticks->seconds gc-time)) 
         (newline)
         (display ";Actual time:\t")
         (write (internal-time/ticks->seconds real-time))
         (newline))))))
